import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { NextUIProvider } from "@nextui-org/react";
import "./globals.css";
import NavBar from "../components/NavBar";
import { inter } from "@/app/ui/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased max-w-full`}>
        <NextUIProvider>
          <ThemeProvider attribute="class">
            <div className="md:px-20 md:pt-10">
              <NavBar />
            </div>
            <div className="px-6 md:px-32 md:mt-10 mt-6">{children}</div>
          </ThemeProvider>
        </NextUIProvider>
      </body>
    </html>
  );
}
